Silence warning in bison generated code
Clang 15 issues a warning about the bison generated code, causing a
build failure when configured with `--enable-werror`:

    parse.c:2499:9: error: variable 'yynerrs' set but not used [-Werror,-Wunused-but-set-variable]
        int yynerrs = 0;
            ^